### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by gaearon** [vriad/devii#2]
Couldn't find a link to an online demo. Seems like it might be useful!

**Comment by vriad** [comment]
@gaearon wow hello! 

Just put one up at https://devii.dev and updated the README/repo accordingly 🤙  Thanks for the motivation :)

**Comment by vriad** [comment]
@gaearon oh I made a really dumb joke on the homepage. It's clear it's a joke but I'm happy to take it down if you don't like it:

![Screen Shot 2020-07-10 at 6 25 24 PM](https://user-images.githubusercontent.com/3084745/87213555-bb583280-c2da-11ea-861a-2b006cc8ec09.png)
